---
title: "Linear Models"
output: github_document
---
Load key packages.
```{r, echo =FALSE, message = FALSE}
library(tidyverse)
library(p8105.datasets)

set.seed(1)

```
Do soome data cleaninig.
```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(stars = review_scores_location / 2) |> 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) |> 
  filter(borough != "Staten Island") |> 
  select(price, stars, borough, neighborhood, room_type) %>% 
  mutate(
    borough = fct_infreq(borough),
    room_type = fct_infreq(room_type)
  )
```

## Fit some models.

Start relatively simple

```{r}
fit = lm(price ~ stars, data= nyc_airbnb)

summary(fit)

names(summary(fit))

coef(fit)

#formatted in table
fit %>% 
  broom::tidy() %>% 
  select(term,estimate,p.value)

fit %>% 
  broom::glance()
```

Try a bit more complex.

```{r}
fit = 
  lm(price ~ stars + borough, data = nyc_airbnb)

fit %>% 
  broom::tidy() %>% 
  select(term, estimate, p.value) %>% 
  mutate(
    term = str_replace(term, "borough", "Borough: ")
  ) %>% 
  knitr:::kable(digits = 3)
```





